- connector.go
- object_manager.go
- objects.go
Basic functionality to manage Network View, Network and
Fixed Address objects.
> Initial version of infoblox-go-client

- object_manager.go
Move attributes to newly created InfobloxDriver class where they
should reside.
> Refactor IPAM

- connector.go
- object_manager.go
- objects.go
Enhanced Infoblox objects to steamline serializing to/from
http request.
> Refactor Infoblox objects

- object_manager.go
- objects.go
Add support for EAdefinition object.
Enable Infoblox object factory method to accept initial value.
> Add EADefinition object

- connector.go
- connector_test.go
- infoblox_go_client_suite_test.go
- object_manager.go
- object_manager_test.go
- objects.go
- objects_test.go
Added unit tests for objects.go
Added unit tests for object_manager.go
Refactored Connector class to enhance DI
Added unit tests for connector.go
> Unit Tests

- connector.go
- object_manager.go
- object_manager_test.go
- objects.go
This patch adds support for the 'Request' NIOS object.
IBConnector UpdateObject method is also implemented in this patch.
> Add Request object and implement IBConnector UpdateObject 

- connector.go
- lock.go
- object_manager.go
- object_manager_test.go
- objects.go
This patch adds distributed locking on network view
for concurrent access to resources in a network view.
> Add Distributed Network View Lock

- connector.go
- objects.go
Added support for UserProfile object and validated basic auth and reachability
while creating the connector.
> Added UserProfile object and validated basic auth and reachability.

- lock.go
> fix logrus dependency 

- README.md
Show usage of Logout method as introduced in #36.
It would be nice if this could warrant a new release so there is a well defined version where you can use the session support.
> Show newly added Logout() method in example.

- connector.go
- connector_test.go
For cloud platform support modified at connector.go
> cloud platform support

- connector_test.go
Added forced proxy implementation in connector_test.go
> forced Proxy test case

- connector_test.go
Reverts infobloxopen/infoblox-go-client#63
Still need to refine the test case.
> Revert "forced Proxy test case"

- objects.go
- objects_test.go
added field ‘name’ in return_field slice of Fixedaddress struct
> 'name' field added in Fixedaddress struct

- connector.go
- connector_test.go
- object_manager.go
- objects.go
CP member using  the objects(ex: network view) created in Grid Master
> CP member to get  GM objects

- connector_test.go
There are two different test cases, one for forceProxy := true and one for forceProxy:=false, and the two cases are  inside different instances of It() blocks.
> modified test cases for force proxy

- connector.go
- infoblox_go_client_suite_test.go
- lock.go
- object_manager.go
- object_manager_test.go
- objects_test.go
* go fmt
* always put external imports to bottom
> Go fmt and restructure imports

- object_manager.go
- object_manager_test.go
Add DeleteNetworkView with a test also sorting functions on interface
This addresses issue #92
> Add DeleteNetworkView with tests

- object_manager.go
- object_manager_test.go
> Remove unused params from GetHostRecord method

- object_manager.go
This pull request adds the feature to update A and CNAME records
> Add feature to update A and CNAME records

- object_manager.go
- object_manager_test.go
- objects.go
- objects_test.go
As part of phase 3 deliverables below are the features added:
- Support for AAAA record(CRUD operations)
- Update operation for A, CNAME and PTR records
- Get operation for CNAME and PTR records(both by reference and attributes)
- Added IPv6 support for PTR record
- EA and TTL support for A, AAAA, CNAME and PTR records
Solves #116 #110 #91 #86 #82
> Deliverables-3

- object_manager.go
- object_manager_test.go
- objects.go
- objects_test.go
- Added default value of network view in AllocateIP, CreateHostRecord and CreatePTRRecord Function
- Added update using next available IP feature for UpdateHostRecord and UpdatePTRRecord functions
- Removed pointers from EnableDns, EnableDhcp and UseTtl flags
- Changed naming convention to UseTtl and Ttl in RecordA structure
- Added apt UTs and updated respective UTs
- Added update IPv4 and IPv6 address feature for Fixed address
> Optimized functions

- connector_test.go
- lock.go
- object_manager.go
- object_manager_test.go
- objects.go
- objects_test.go
- Extended support to perform CRUD operations on comments and EAs of Network view
- Update name of the network view
- Added GetARecord function
> Updated CRUD operations on network view and added GetARecord function

- README.md
Update instructions on downloading latest version of plugin.
> Update on new release

- README.md
This PR updates the README file with seperate config's for hostConfig and authConfig(either with username and password or certificates)
> Updates README file in configuration

- connector.go
- objects_generated.go
- utils.go
If the terraform EA search through the multi value can be possible with this fix.
> Fixes terraform issue for EA search through multi value

- CHANGELOG.md
- README.md
This PR has updated CHANGELOG file with release summary and major changes for the new release.
> Updates CHANGELOG file with release summary documentation

- object_manager_apps.go
- object_manager_apps_test.go
- objects.go
> Fixed dhcp app struct

- CHANGELOG.md
- README.md
Contains v2.6.0 release notes.
> Updates Documentation of CHANGELOG and README

- object_manager.go
Fix for NPA-165 : - EAs are not retrieved by zone_delegated datasource
> Fix for NPA-165

- e2e_tests/wapi_framework_test.go
- object_manager_network_container_test.go
- object_manager_network_test.go
Added negative scenarios to next-available testcases
> adding negative scenarios to next-available testcases

- e2e_tests/wapi_framework_test.go
> E2E testcases-goclient

- object_manager_host_record.go
disable field added to return fields in NewEmptyHostRecord()
> disable field added to return fields

- object_manager_dtc_pool.go
Updating error message in updateServerReferences and getMonitorReference
> Updating error message in updateServerReferences and getMonitorReference

- object_manager_dtc_lbdn.go
- object_manager_dtc_pool.go
- object_manager_dtc_pool_test.go
- object_manager_dtc_server.go
1. updating error messages.
2. condition to unset consolidated_monitors field when consolidated_monitors is empty slice and auto_consolidated_monitors is set to false
> NPA-300, NPA-301 fix

- object_manager_dtc_pool.go
1. NPA-305: Added ConsolidatedMonitorsWrapper struct for handling of ConsolidatedMonitors field creation, deletion and modification.
2. NPA-301: Improved error messages.
> NPA-301,305 Fix

- object_manager_dtc_lbdn.go
NPA-307 - Updated the getAuthZones function
> [FIX] - NPA-307 - Updated the getAuthZones function

- object_manager_dtc_pool_test.go
- object_manager_dtc_server_test.go
added test cases for consolidated monitors 
made changes for dtc pool and dtc server test cases
> added test cases for consolidated monitors 

- e2e_tests/wapi_framework_test.go
- object_manager.go
- object_manager_dtc_pool.go
- object_manager_fixed_address.go
- object_manager_fixed_address_test.go
- object_manager_ipv4_shared_network.go
- object_manager_ipv4_shared_network_test.go
- object_manager_range_test.go
- objects.go
- objects_test.go
test case changes  and fixed address code changes
> test case changes 
