object_manager.go

Regexp used to extract network view name did not allow '-'.
Fixed by relaxing the pattern used.

Fix regexp used to parse object ref

---

object_manager.go

Instead of generating a random MAC address when none is provided,
use "00:00:00:00:00:00" instead.

Use zero MAC address when none is provided

---

object_manager.go

For ReleasePool request, delete network from Infoblox if pool
belongs to local address space.

Delete network from Infoblox

---

object_manager.go

WAPI 2.0 for Cloud requires "VM ID" EA for Fixed Address object.

Add "VM ID" EA

---

connector.go
object_manager.go

Connector class support specifying a PEM format certificate file to be
used for verifying Infoblox server certificate.
Minor refactoring to better handle SSL certificate verification error.

Add SSL verify support

---

object_manager.go

DeleteLocalNetwork() should more appropriately named simply
DeleteNetwork().

Rename DeleteLocalNetwork() method

---

object_manager.go

Fix so that ReleaseIP() returns gracefully if IP already been released.

Release IP fix

---

object_manager.go
objects.go

1) Added return_fields so that all fields supported by go objects are
returned by Infoblox.
2) Allow specifying Cidr when searching for fixed address in Infoblox.

Add return_fields, use cidr to get fixed address

---

connector.go
connector_test.go
object_manager.go
object_manager_test.go
objects.go
objects_test.go

This patch passes EA's in body instead of query string because of
the issue #18.
Also Fixes issues where error is not returned when there is error
in the request response body.

Search EA's by passing in body instead of query string

---

object_manager.go

UpdateFixedAddress is required to support cni_spec 0.3.1 as with
cni release v0.4.0: https://github.com/containernetworking/cni/releases/tag/v0.4.0
The mac_address of the interface was allocated based on the ip_address on all the
network drivers, for example:
https://github.com/containernetworking/cni/blob/v0.4.0/plugins/main/macvlan/macvlan.go#L153

Added support for UpdateFixedAddress in client

---

objects.go
objects_test.go

Neither the infobloxopen/infoblox-go-client:master nor the khris.richardson/infoblox-go-client:k8s-external-dns-provider passed for me, but I tried to remain consistent with the other unit tests.
The AllRecords test is commented out, since I suspect it may not pass given that it's a read-only object.

add objects required by Kubernetes external-dns provider

---

objects.go
objects_test.go

This PR will facilitate preventing the Infoblox external-dns provider for Kubernetes (WIP) from creating an `A` record if a corresponding `Host` record already exists.

add support for record:host

---

objects.go

Output prior to change:
```
$ go vet
objects.go:20: struct field objectType has json tag but is not exported
objects.go:21: struct field returnFields has json tag but is not exported
objects.go:22: struct field eaSearch has json tag but is not exported
exit status 1
```

Make 'go vet' happy.

---

README.md
connector.go

* Long overdue readme file for the client
* set httpRequestTimeout & httpPoolConnections while creating TransportConfig
Currently NewTransportConfig takes an "httpRequestTimeout int" but it is not
used to fill in the returned "cfg TransportConfig", which is wrong. Fixing the
issue in this patch

Add readme file

---

connector.go

While here declare HttpRequestTimeout as a time.Duration so there is no
need for a type conversion.

Replace hardcoded 1000000000 with time.Second.

---

connector.go

This makes multiple requests use the same login session instead of
creating one login event per request.
A Logout() method is added to the *Connector so you can invalidate the
cookie when you are done, for example using a defer statement.
Below is an example code snippet  used when testing this. Before the change there will be two login events in the audit log, even if I only perform one request (becase of validateConnector() performing an initial request). After the change only a single login event is logged, and the newly added conn.Logout() will lead to an logout event in the audit log:
```
package main
import (
"fmt"
ibclient "github.com/infobloxopen/infoblox-go-client"
"log"
)
func main() {
hostConfig := ibclient.HostConfig{
Host:     "ipam.example.com",
Version:  "x.x.x",
Port: …
```

Support login session using ibapauth cookie.

---

connector.go

Fixes golint suggestion:
```
connector.go:327:1: exported method Connector.Logout should have comment or be unexported
```

Document Logout() method.

---

connector_test.go

Fixes:
```
connector_test.go:94:5: var expectedUrlStr should be expectedURLStr
connector_test.go:106:5: var expectedUrlStr should be expectedURLStr
connector_test.go:117:5: var expectedUrlStr should be expectedURLStr
```

connector_test.go: Fix internal golint suggestions.

---

lock.go

Fixes:
```
lock.go:210:10: if block ends with a return statement, so drop this else and outdent its block
```

lock.go: Fix internal golint suggestion.

---

connector.go

Fixes:
```
connector.go:49:10: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)
connector.go:119:6: func getHttpResponseError should be getHTTPResponseError
connector.go:197:6: var objJson should be objJSON
connector.go:208:3: var eaSearchJson should be eaSearchJSON
```

connector.go: Fix internal golint suggestions.

---

objects.go

Fixes:
```
objects.go:503:1: receiver name v should be consistent with previous receiver name val for EADefListValue
```

objects.go: Fix internal golint suggestions.

---

object_manager.go

Fixes:
```
object_manager.go:45:41: method parameter cloudApiOwned should be cloudAPIOwned
object_manager.go:151:9: should omit 2nd value from range; this loop is equivalent to `for k := range ...`
```

object_manager.go: Fix internal golint suggestions

---

object_manager.go
object_manager_test.go
objects.go

Presently 'name' field is left out so updating that field with
vmID value

Updation of name field in FixedAddress record

---

connector.go

Right now the `cfg.HttpRequestTimeout` is only being applied to the `http.Transport.ResponseHeaderTimeout`. However, it should be applied to the entire `http.Client`. See the Client Timeout section of https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/ for more information.
`http.Client` reference: https://golang.org/pkg/net/http/#Client

apply request timeout to http.Client

---

objects.go

Ipv4Addr field added to HostRecord struct at objects.go.
https://github.com/infobloxopen/infoblox-go-client/issues/59

Ipv4Addr field added to HostRecord struct

---

object_manager.go
object_manager_test.go

Refactoring EA value for other records
EA's were missed for CNAME records in previous commit and they are
required while using CP member

Adding EA to CNAME records

---

objects.go
objects_test.go

* Otherwise GetZoneDelegated returns the zone
with empty DelegateTo

Return delegate_to field for new ZoneDelegated object

---

objects.go
objects_test.go

The client crashes when the value of an extensible attribute is an array.
This pull request tries to handle this case.
The error message when the ea is an array is: 
```
panic: interface conversion: interface {} is []interface {}, not string
goroutine 1 [running]:
github.com/mhermida/infoblox-go-client.(*EA).UnmarshalJSON(0xc0000107e0, 0xc0001ac300, 0xbf, 0xc0, 0x7f64d6078110, 0xc0000107e0)
/home/marcos/dev/go/hellogo/src/github.com/mhermida/infoblox-go-client/objects.go:552 +0x4cf
encoding/json.(*decodeState).object(0xc0000a7130, 0x8637a0, 0xc0000107e0, 0x16, 0xc0000a7158, 0xc00038ca7b)
...
```
Full stack error is attached.
[error_message.txt](https://github.com/infobloxopen/infoblox-go-client/files/4219860/error_message.txt)

Add support for array values in extensible attributes

---

object_manager.go

The CreateHostRecord method return a wrong error in case the request involve an already existing host record:
Contents:
{ "Error": "AdmConProtoError: Field is not searchable: configure_for_dns", 
"code": "Client.Ibap.Proto", 
"text": "Field is not searchable: configure_for_dns"
}
This error comes from the getObject and not from the createObject, indeed in case of error I should be able to know why I couldn't create the requested object.
Thanks,
F.

Update object_manager.go to get already exist host record error

---

object_manager.go
object_manager_test.go

Add option to skip getting cloud attributes for on-prem deployments
Fixes #79

Omit cloud attrs

---

connector.go

Ading TLS renagotiate flag. In client's environment all interactions fail due to renagotiate not being enabled.

Adding tls renagotiate

---

connector.go
object_manager.go
object_manager_test.go
objects.go
objects_test.go
record_ns.go

There were some missing pieces for using this client for our purposes.
We integrated Infoblox DNS as a provider in our project external-dns-management (https://github.com/gardener/external-dns-management/pull/98).
For this purpose, we added:
- TTL fields for TXT and CNAME records
There was also an inconsistency in writing `Ttl` or `TTL`. As most code uses `Ttl`, this convention is used here too
- struct RecordNS to be able to query NS records
- `ProxyUrl` as option in the TransportConfig. In our development environment, the Infoblox DNS grid is only reachable through a reverse proxy.

TTL for TXT and CNAME record, added RecordNS, ProxyUrl to TransportConfig

---

connector.go

With this change, users can use the de facto standard HTTP(S)_PROXY environment variables instead of having to specify them manually. 
See https://golang.org/pkg/net/http/#ProxyFromEnvironment
I think using the environment variables is what you often get by [default](https://github.com/golang/go/blob/2e59cc5fb4e81fbd2ee9f662caa707c1138bf5ae/src/net/http/transport.go#L44)?? (sorry, I'm new to go)

Use proxy env variables if explicit proxy not set

---

object_manager.go

Adds a compile-time check to the interface to make sure it stays in sync with the actual implementation.

Add compile-time interface check

---

go.mod

The new release v2.0.0 cannot be imported anymore.
Trying to import `github.com/infobloxopen/infoblox-go-client v2.0.0` results in this error with golang 1.16
```txt
go: errors parsing go.mod:
.../go.mod:19:2: require github.com/infobloxopen/infoblox-go-client: version "v2.0.0" invalid: should be v0 or v1, not v2
```
Trying to import `github.com/infobloxopen/infoblox-go-client/v2 v2.0.0`
```txt
go: github.com/infobloxopen/infoblox-go-client/v2@v2.0.0: go.mod has non-.../v2 module path "github.com/infobloxopen/infoblox-go-client" (and .../v2/go.mod does not exist) at revision v2.0.0
```
The simplest resolution is to adjust the module in `go.mod`

fix go.mod module for v2.x.x

---

README.md

A request has been made by community users and developers to remove develop branch and maintain only master branch. Since it created more confusion and also considerable efforts to maintain 2 branches.

remove develop branch

---

connector.go

* The messages returned by the `tls.X509KeyPair` function call were not clear for a user.
* Related to the ticket `NIOS-84878`.
* Supplemented error messages returned by tls.X509KeyPair function call
with "Invalid certificate key pair:" prefix.
@skudriavtsev

Clarified the error messages returned by the tls.X509KeyPair function

---

README.md
object_manager.go
object_manager_network_container.go
object_manager_network_container_test.go
objects.go
utils.go

Add Allocate Network Container NIOS operation. This is used to dynamically create network containers to be used with infoblox terraform.
Link to Infoblox Terraform Issue.
infobloxopen/terraform-provider-infoblox#157

Added NIOS operation to allocate network container

---

object_manager_aaaa-record.go

This is removes unnecessary restriction,  for not allowing uppercase letters in FQDN for AAAA Record.

Fixes usage of uppercase letters in FQDN for AAAA-Record

---

README.md
connector.go

Updates HostConfig with `Scheme` and use default "https" if Scheme is not "http". 
No breaking changes.
Updates example in Readme to demonstrate that Host is configurable with Scheme.

Update HostConfig with Scheme

---

connector.go
connector_test.go

the new type can be used like the following
``` go
header := make(http.Header)
header.Add("x", "1")
header.Add("y", "2")
wrb, _ := NewWapiRequestBuilder(hostCfg, authCfg)
wrbh, err := NewWapiRequestBuilderWithHeaders(wrb, header)

Introduce request builder with headers

---

objects.go

* Remove `omitempty` json tag from DNS and DHCP struct
* As in request build method, json marshal will remove zero values of the field. But EnableDns/EnableDhcp is required in the body.

Remove omitempty json tag from dns/dhcp struct

---

object_manager.go

Add a function to retrieve ZoneDelegation by ref, as a prerequisite for a Zone Delegation resource

Add func GetZoneDelegatedByRef

---

e2e_tests/wapi_framework_test.go

added E2E test cases for Forward zone.

added E2E test cases for Forward zone.

---

object_manager_forward_zone_test.go
object_manager_test.go

Forward zone unit test
**Test result for forward zone :**
```
go test -v --ginkgo.focus="Object Manager: forward zone" --ginkgo.trace
=== RUN   TestInfobloxGoClient
Running Suite: InfobloxGoClient Suite - /Users/jchhatbar/GolandProjects/dev/infoblox-go-client
==============================================================================================
Random Seed: 1718801835
Will run 5 of 581 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS …
```

Forward zone unit test
